# Generated by Django 5.2.10 on 2026-01-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='career_path',
        ),
    ]
