# Generated by Django 5.2.10 on 2026-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0002_remove_joinrequest_score_remove_project_career_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_req',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
