# Generated by Django 5.2.10 on 2026-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0003_project_role_project_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='request_type',
            field=models.CharField(choices=[('APPLICATION', 'Applied'), ('INVITATION', 'Invited')], default=None, max_length=50),
        ),
    ]
