# Generated by Django 5.2.10 on 2026-01-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0004_project_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='request_type',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='request_type',
            field=models.CharField(choices=[('APPLICATION', 'Applied'), ('INVITATION', 'Invited')], default=None, max_length=50),
        ),
    ]
