# Generated by Django 5.2.10 on 2026-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0005_remove_project_request_type_joinrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='request_type',
            field=models.CharField(choices=[('APPLICATION', 'Applied'), ('INVITATION', 'Invited')], default='APPLICATION', max_length=50),
        ),
    ]
