# Generated by Django 5.2.10 on 2026-01-17 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0006_alter_joinrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='project',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('project_invite', 'Project Invitation'), ('join_request', 'Join Request'), ('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('general', 'General Alert')], default='general', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
