# Generated by Django 5.2.10 on 2026-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0007_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='match_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
