# Generated by Django 5.2.10 on 2026-01-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devsync', '0008_joinrequest_match_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='match_score',
        ),
    ]
